name: unittest

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@master
        with:
          context: .devcontainer
          tags: libcoffee
          push: false

      - name: Type check
        uses: addnab/docker-run-action@v3
        with:
          image: libcoffee
          options: -v ${{ github.workspace }}:/work
          run: |
            cd /work
            pip install -e .
            mypy --strict -p libcoffee --explicit-package-bases

      - name: Unittest
        uses: addnab/docker-run-action@v3
        with:
          image: libcoffee
          options: -v ${{ github.workspace }}:/work
          run: |
            cd /work
            pip install -e .
            python -m pytest .